### PR TITLE
proposing fix to JIT

### PR DESCRIPTION
**Pull request by ziosante**
Fixes src\jit\compemu.cpp

Changes proposed in this pull request:

   - fixed JIT: link.l sp,#, link.w sp,# and unlk sp (LINK.L, LINK.W, UNLK.L)
      not really heavy used on amigaos, but at least this fixes cputest
   - fixed JIT: EORSR.B and ORSR.B, now WB 3.9 shell should work well when JIT enabled

Hi,
I used amiberry for a while on a raspberry p2 with JIT enabled and found that OS 3.9 shell does not work well, sometimes output text freeze and you have to click with mouse out of the shell to resume the text output. Sometimes the shell close unexpected.
I've made some test and found that EORSR.B and ORSR.B seems to be buggy.
Since I love Amiga and emulators I suggest these fixes.

P.S.: congrats for your great work with this emulator.

Thanks,
Sante

### CODE REVIEW

**Comment by midwan** [comment]
@ziosante 
Thanks a lot!
I'll just run a few tests to make sure it works fine, then we can merge it in.

**Comment by ziosante** [comment]
Thanks!
This is my first contribute to a github project. I created an account just some minutes ago.
I hope I can contribute more in future.

**Comment by midwan** [comment]
@ziosante 
Merged, thanks again!

**Comment by solskogen** [comment]
This broke 3.1.4 (no icons on the desktop)

**Comment by midwan** [comment]
@ziosante 
Could we take another look at it please?

**Comment by ziosante** [comment]
Yes,
I'll make some test

**Comment by ziosante** [comment]
I've not tested OS 3.1.4 before.
I replaced the compemu.cpp with the one before my modification, compiled and the result is the same: with JIT enabled OS 3.1.4 seems to hang (no icons on desktop).
So maybe could be something other. I'll try to continue investigation.

**Comment by solskogen** [comment]
When running on Manjaro ARM (64bit) it does not seem to be a problem. Only
on 32bit OS/kernel.

**Comment by solskogen** [comment]
Did you have any luck, @ziosante ?

**Comment by ziosante** [comment]
> 
> 
> Did you have any luck, @ziosante ?

Sorry, busy on other activities

**Pull request merged**
