### PR TITLE
Support for Odroid XU4

### PR DESCRIPTION
**Pull request by bspinner**
Added the target for Odroid XU4.
Not sure whether there are better/more flags.

Feel free to add things to test/fix before accepting this request.

Things possibly broken:
- [ ] Mouse in main menu (works in Workbench)

### CODE REVIEW

**Comment by midwan** [comment]
Thanks! :)

**Comment by bspinner** [comment]
@midwan Please check additional bullet points of possible broken things.
Maybe some stuff is already known and not XU4 specific.

**Comment by blinkydoos** [comment]
>  Sometimes the screen is cut off on the left side (e.g. CD32 kickstart animation)

This also happens on Raspberry SDL1 and SDL2 builds. As shown in the issue below (I think it needs reopening).

https://github.com/midwan/amiberry/issues/100#issuecomment-303978138

The resolution needs increasing but you can't on SDL2.

**Comment by bspinner** [comment]
I've just setup retropie on my odroid xu4 and now sound works too.
The JIT problem I've observed yesterday didn't occur again.
State of the Art demo works fine with sound and JIT now.

Does the mouse pointer in main menu work on RPis?

**Comment by midwan** [comment]
@bspinner 
Yes, the mouse pointer works on the RPi, never seen a problem with that so far. Perhaps it's related to the fact that we've replaced the mouse pointer image on SDL2, I'm not sure without being able to recreate this.

JIT can work with any CPU from 020 onwards. I have a test environment with 040/JIT booting Workbench 3.9 which I use every time I build a new version. What did you test it with exactly? What config options did you use?

**Comment by bspinner** [comment]
I can use the mouse but the pointer isn't displayed. So yes, likely connected to the mouse pointer image.

When compiling with DEBUG flag, this happens:
```
In file included from src/jit/compemu_support.cpp:1331:0:
src/jit/compemu_midfunc_arm.cpp: In function ‘void flush_cpu_icache(void*, void*)’:
src/jit/compemu_midfunc_arm.cpp:473:1: error: r7 cannot be used in asm here
 }
 ^
<builtin>: recipe for target 'src/jit/compemu_support.o' failed
```

**Comment by midwan** [comment]
@bspinner Obvious question here, but have you checked the kickstart ROMs you have?
The A4000 has a different ROM than the A1200, and if you have an Amiga Forever copy then you also need the keyfile in the same directory...

Testing A4000 Quickstart configuration here (on a Pi 3) works normally. I am using the Amiga Forever ROMs with the relevant keyfile, and it picks the right one for each model (A500, A1200, A4000, CD32, etc).

The error you got with the DEBUG flag is interesting however, I wonder if it's related to the CPU architecture?

**Comment by bspinner** [comment]
> Obvious question here, but have you checked the kickstart ROMs you have?
The A4000 has a different ROM than the A1200, and if you have an Amiga Forever copy then you also need the keyfile in the same directory...

The kickstarts are fine. Just checked again.

Regarding the DEBUG flag error: https://tls.mbed.org/kb/development/arm-thumb-error-r7-cannot-be-used-in-asm-here
> Reason
>
> The assembly code in bn_mul.h is optimized for the ARM platform and uses some registers, including r7 to efficiently do an operation. GCC also uses r7 as the frame pointer under ARM Thumb assembly.
>
> Solution
> 
> Add -fomit-frame-pointer to your GCC compiler options.
> 
> If you have already added -O, -O2, etc you do not need to add -fomit-frame-pointer as the optimization options already include it on most systems by default.

**Comment by bspinner** [comment]
I finally got the debugging via VC++ working.

The cursor is not displayed because this
```c
if (cursorSurface)
{
    cursor = SDL_CreateColorCursor(cursorSurface, 0, 0);
}
```
Leads to an `nullptr`, so the call failed. `SDL_error` says *Cursors are not currently supported*. 🤔

**Comment by midwan** [comment]
Aha, that should be an easy fix then.
We can use "#ifdef" checks around the cursorSurface assignment, it shouldn't be set to anything if the system doesn't support it - then this piece above would skip assigning the cursor (since "cursorSurface" is nullptr).

**Comment by Uukrull** [comment]
@bspinner: How did you get VC debugging working on your Odroid? That would help me a lot with my S905X box.

**Comment by bspinner** [comment]
> We can use "#ifdef" checks around the cursorSurface assignment

I'd recommend we use the information we get at runtime. Just free the surface and perform checks at places where needed. `#ifdef` would mean, we can be 100% sure there's no user out there, where that function won't return an error due to other reasons.

@Uukrull I just had to make minor adjustments to the existing solution file (credentials, paths, add `PLATFORM=xu4` and most importantly `DEBUG=1` to make). And of course install the gdb remote server on my xu4.

**Pull request merged**
