### PR TITLE
Hack that makes international keyboards usable

### PR DESCRIPTION
**Pull request by rabejens**
Quick hack that makes at least German keyboards work better. Backslash is on F11, the old backslash key (which is Hash on a German keyboard) produces Hash/Circumflex when the keymap is set to German on the Amiga side, and the less/greater key on German keyboards is now working.

### CODE REVIEW

**Comment by midwan** [comment]
@rabejens 
I'm delaying this a bit until I have some time to work on it, over the next few days.
I'd prefer a solution that doesn't interfere with the existing layout, as we discussed briefly. We can take some ideas from FS-UAE/WinUAE which have something similar and improve on that as necessary.

I think it's best if we work on it on a separate branch in the meantime, to avoid pushing anything in the working one that might break it. Perhaps something like sdl2-intl.

Do you agree?

**Comment by rabejens** [comment]
Yes, I agree with you on that.

I would propose the following approach:

- Enable the less/greater key in general (maybe clean up the dirty hack I did) - this won't hurt; US keyboards are simply missing this key.
- add two options to the Input settings in the GUI:
  - A combo box to select how the "Hash" / "Backslash" key on the PC keyboard should behave on the Amiga side - should it input backslashes (default) or function as the "Hash" key (Code 0x2B)
  - A key that can be mapped to the Amiga's backslash key if the former option was set to function as key 0x2B
  - Alternatively: Make Backslash / Hash keys on the Amiga side configurable in the GUI. I pinned the backslash to F11 in my version, as this is aproximately where the backslash is on the German Amiga keyboard, but there might be some "multimedia" keyboards that have some additional keys where one could be used as the backslash.

Unfortunately I don't have time to work on that by myself for the next weeks, and I haven't yet figured out the GUI part of Amiberry, but maybe these proposals are not that hard for you (or another one who wants to give it a try).

**Comment by midwan** [comment]
@rabejens 
No worries, I can take care of it :)

**Comment by midwan** [comment]
Hi @rabejens 
With the latest commits in the "dev" branch, most of what you did is implemented except changing the backslash key to F11. You may want to have another look at the current state. :)

**Pull request closed without merging**
